[package]
name = "extract-md-links"
version = "0.1.0"
authors = ["Chris Krycho <hello@chriskrycho.com>"]
edition = "2018"

[dependencies]
pulldown-cmark = { version = "0.2.0", default-features = false }
